# Generated by Django 5.0.4 on 2024-05-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='movement_type',
            field=models.CharField(choices=[('run', 'Run'), ('gallop', 'Gallop'), ('hop', 'Hop'), ('leap', 'Leap'), ('horizontal_jump', 'Horizontal Jump'), ('slide', 'Slide'), ('skip', 'Skip')], default='run', max_length=20),
        ),
    ]
